# ********RoostGPT********
"""
Test generated by RoostGPT for test python-audio using AI Type Claude AI and AI Model claude-sonnet-4-20250514

ROOST_METHOD_HASH=set_coefficients_6e86de812a
ROOST_METHOD_SIG_HASH=set_coefficients_9310de71c7


Scenario 1: Valid Coefficients with Correct Length
Details:
  TestName: test_set_coefficients_valid_input_correct_length
  Description: Verify that the method correctly sets both a_coeffs and b_coeffs when provided with lists of the expected length (order + 1) for both coefficient arrays.
Execution:
  Arrange: Create an IIRFilter instance with a specific order (e.g., order=2). Prepare valid coefficient lists where both a_coeffs and b_coeffs have length equal to order + 1 (3 elements each).
  Act: Call set_coefficients method with the prepared coefficient lists.
  Assert: Verify that self.a_coeffs and self.b_coeffs are set to the provided values and that no exception is raised.
Validation:
  This test ensures the primary happy path functionality works correctly when users provide properly sized coefficient arrays, which is the most common use case for filter configuration.

Scenario 2: Missing a0 Coefficient Auto-Addition
Details:
  TestName: test_set_coefficients_missing_a0_coefficient
  Description: Verify that when a_coeffs has fewer elements than required (specifically order elements instead of order + 1), the method automatically prepends 1.0 as the a0 coefficient.
Execution:
  Arrange: Create an IIRFilter instance with order=2. Prepare a_coeffs with only 2 elements (missing a0) and b_coeffs with 3 elements.
  Act: Call set_coefficients method with the prepared coefficient lists.
  Assert: Verify that self.a_coeffs has 3 elements with 1.0 as the first element, followed by the original a_coeffs values, and that self.b_coeffs is set correctly.
Validation:
  This test validates the automatic a0 coefficient handling feature, which provides convenience for users working with filter design functions that may omit the a0 coefficient.

Scenario 3: Invalid a_coeffs Length Too Short
Details:
  TestName: test_set_coefficients_a_coeffs_too_short
  Description: Verify that the method raises a ValueError when a_coeffs has significantly fewer elements than required (less than order elements).
Execution:
  Arrange: Create an IIRFilter instance with order=3. Prepare a_coeffs with only 2 elements and b_coeffs with 4 elements.
  Act: Call set_coefficients method with the prepared coefficient lists.
  Assert: Verify that a ValueError is raised with an appropriate error message indicating the expected number of elements for a_coeffs.
Validation:
  This test ensures proper error handling when users provide insufficient a_coefficients, preventing filter misconfiguration that could lead to incorrect signal processing results.

Scenario 4: Invalid a_coeffs Length Too Long
Details:
  TestName: test_set_coefficients_a_coeffs_too_long
  Description: Verify that the method raises a ValueError when a_coeffs has more elements than required (more than order + 1 elements).
Execution:
  Arrange: Create an IIRFilter instance with order=2. Prepare a_coeffs with 5 elements and b_coeffs with 3 elements.
  Act: Call set_coefficients method with the prepared coefficient lists.
  Assert: Verify that a ValueError is raised with an appropriate error message indicating the expected number of elements for a_coeffs.
Validation:
  This test ensures that oversized coefficient arrays are rejected, maintaining filter order consistency and preventing potential computational errors or unexpected behavior.

Scenario 5: Invalid b_coeffs Length Too Short
Details:
  TestName: test_set_coefficients_b_coeffs_too_short
  Description: Verify that the method raises a ValueError when b_coeffs has fewer elements than required (less than order + 1 elements).
Execution:
  Arrange: Create an IIRFilter instance with order=2. Prepare a_coeffs with 3 elements and b_coeffs with only 2 elements.
  Act: Call set_coefficients method with the prepared coefficient lists.
  Assert: Verify that a ValueError is raised with an appropriate error message indicating the expected number of elements for b_coeffs.
Validation:
  This test validates proper error handling for insufficient b_coefficients, ensuring that the filter cannot be configured with incomplete feedforward coefficients that would compromise filter functionality.

Scenario 6: Invalid b_coeffs Length Too Long
Details:
  TestName: test_set_coefficients_b_coeffs_too_long
  Description: Verify that the method raises a ValueError when b_coeffs has more elements than required (more than order + 1 elements).
Execution:
  Arrange: Create an IIRFilter instance with order=2. Prepare a_coeffs with 3 elements and b_coeffs with 5 elements.
  Act: Call set_coefficients method with the prepared coefficient lists.
  Assert: Verify that a ValueError is raised with an appropriate error message indicating the expected number of elements for b_coeffs.
Validation:
  This test ensures that oversized b_coefficient arrays are properly rejected, maintaining consistency in filter order and preventing potential issues in filter implementation.

Scenario 7: Empty Coefficient Lists
Details:
  TestName: test_set_coefficients_empty_lists
  Description: Verify that the method raises appropriate ValueError when either or both coefficient lists are empty.
Execution:
  Arrange: Create an IIRFilter instance with order=1. Prepare empty lists for both a_coeffs and b_coeffs.
  Act: Call set_coefficients method with empty coefficient lists.
  Assert: Verify that a ValueError is raised indicating insufficient coefficient elements.
Validation:
  This test ensures that the method properly handles edge cases with empty input lists, preventing filter configuration with no coefficients which would be mathematically invalid.

Scenario 8: Zero Order Filter Configuration
Details:
  TestName: test_set_coefficients_zero_order_filter
  Description: Verify that the method correctly handles coefficient setting for a zero-order filter (order=0), which should require exactly 1 element in each coefficient array.
Execution:
  Arrange: Create an IIRFilter instance with order=0. Prepare a_coeffs and b_coeffs each with exactly 1 element.
  Act: Call set_coefficients method with single-element coefficient lists.
  Assert: Verify that both coefficient arrays are set correctly without raising any exceptions.
Validation:
  This test validates the method's behavior for the simplest possible filter configuration, ensuring that zero-order filters (simple gain blocks) can be properly configured.

Scenario 9: High Order Filter Configuration
Details:
  TestName: test_set_coefficients_high_order_filter
  Description: Verify that the method correctly handles coefficient setting for high-order filters (e.g., order=10), ensuring scalability of the validation logic.
Execution:
  Arrange: Create an IIRFilter instance with order=10. Prepare a_coeffs and b_coeffs each with exactly 11 elements.
  Act: Call set_coefficients method with the prepared coefficient lists.
  Assert: Verify that both coefficient arrays are set correctly and contain all provided values.
Validation:
  This test ensures that the method scales properly for complex, high-order filters commonly used in advanced signal processing applications, validating that the length checking logic works correctly for larger arrays.

Scenario 10: Coefficient Values Preservation
Details:
  TestName: test_set_coefficients_values_preservation
  Description: Verify that the method preserves the exact numerical values of the provided coefficients, including handling of special float values like very small numbers, negative numbers, and edge cases.
Execution:
  Arrange: Create an IIRFilter instance with order=2. Prepare coefficient lists containing various float values including negative numbers, very small positive numbers, and zero values.
  Act: Call set_coefficients method with the prepared coefficient lists containing diverse numerical values.
  Assert: Verify that all coefficient values are preserved exactly as provided, with no modification or truncation of the numerical values.
Validation:
  This test ensures that the method acts purely as a setter without modifying the coefficient values, which is crucial for maintaining the mathematical integrity of the filter design and ensuring that carefully calculated coefficients from filter design algorithms are preserved exactly.

"""

# ********RoostGPT********
from __future__ import annotations

import pytest
from audio_filters.iir_filter import IIRFilter


class TestIirFilterSetCoefficients:
    
    def test_set_coefficients_valid_input_correct_length(self):
        """Test that valid coefficients with correct length are set properly."""
        # Arrange
        filter_order = 2
        iir_filter = IIRFilter(filter_order)
        a_coeffs = [1.0, -0.5, 0.25]  # 3 elements for order 2
        b_coeffs = [0.1, 0.2, 0.1]    # 3 elements for order 2
        
        # Act
        iir_filter.set_coefficients(a_coeffs, b_coeffs)
        
        # Assert
        assert iir_filter.a_coeffs == a_coeffs, f"Expected a_coeffs to be {a_coeffs}, got {iir_filter.a_coeffs}"
        assert iir_filter.b_coeffs == b_coeffs, f"Expected b_coeffs to be {b_coeffs}, got {iir_filter.b_coeffs}"
        print(f"Successfully set coefficients: a_coeffs={iir_filter.a_coeffs}, b_coeffs={iir_filter.b_coeffs}")

    def test_set_coefficients_missing_a0_coefficient(self):
        """Test that missing a0 coefficient is automatically added as 1.0."""
        # Arrange
        filter_order = 2
        iir_filter = IIRFilter(filter_order)
        a_coeffs = [-0.5, 0.25]       # 2 elements (missing a0)
        b_coeffs = [0.1, 0.2, 0.1]    # 3 elements
        expected_a_coeffs = [1.0, -0.5, 0.25]
        
        # Act
        iir_filter.set_coefficients(a_coeffs, b_coeffs)
        
        # Assert
        assert iir_filter.a_coeffs == expected_a_coeffs, f"Expected a_coeffs to be {expected_a_coeffs}, got {iir_filter.a_coeffs}"
        assert iir_filter.b_coeffs == b_coeffs, f"Expected b_coeffs to be {b_coeffs}, got {iir_filter.b_coeffs}"
        assert len(iir_filter.a_coeffs) == filter_order + 1, f"Expected a_coeffs length to be {filter_order + 1}, got {len(iir_filter.a_coeffs)}"
        print(f"Successfully added a0=1.0: a_coeffs={iir_filter.a_coeffs}")

    def test_set_coefficients_a_coeffs_too_short(self):
        """Test that ValueError is raised when a_coeffs is too short."""
        # Arrange
        filter_order = 3
        iir_filter = IIRFilter(filter_order)
        a_coeffs = [0.5, 0.25]        # 2 elements, need at least 3 for order 3
        b_coeffs = [0.1, 0.2, 0.1, 0.05]  # 4 elements
        
        # Act & Assert
        with pytest.raises(ValueError) as exc_info:
            iir_filter.set_coefficients(a_coeffs, b_coeffs)
        
        expected_msg = f"Expected a_coeffs to have {filter_order + 1} elements for {filter_order}-order filter, got {len(a_coeffs)}"
        assert expected_msg in str(exc_info.value), f"Expected error message to contain '{expected_msg}', got '{str(exc_info.value)}'"
        print(f"Correctly raised ValueError for short a_coeffs: {exc_info.value}")

    def test_set_coefficients_a_coeffs_too_long(self):
        """Test that ValueError is raised when a_coeffs is too long."""
        # Arrange
        filter_order = 2
        iir_filter = IIRFilter(filter_order)
        a_coeffs = [1.0, -0.5, 0.25, 0.1, 0.05]  # 5 elements, need 3 for order 2
        b_coeffs = [0.1, 0.2, 0.1]               # 3 elements
        
        # Act & Assert
        with pytest.raises(ValueError) as exc_info:
            iir_filter.set_coefficients(a_coeffs, b_coeffs)
        
        expected_msg = f"Expected a_coeffs to have {filter_order + 1} elements for {filter_order}-order filter, got {len(a_coeffs)}"
        assert expected_msg in str(exc_info.value), f"Expected error message to contain '{expected_msg}', got '{str(exc_info.value)}'"
        print(f"Correctly raised ValueError for long a_coeffs: {exc_info.value}")

    def test_set_coefficients_b_coeffs_too_short(self):
        """Test that ValueError is raised when b_coeffs is too short."""
        # Arrange
        filter_order = 2
        iir_filter = IIRFilter(filter_order)
        a_coeffs = [1.0, -0.5, 0.25]  # 3 elements
        b_coeffs = [0.1, 0.2]         # 2 elements, need 3 for order 2
        
        # Act & Assert
        with pytest.raises(ValueError) as exc_info:
            iir_filter.set_coefficients(a_coeffs, b_coeffs)
        
        # Note: There's a bug in the original code - it shows len(a_coeffs) instead of len(b_coeffs)
        # TODO: Fix the error message in the original code to show len(b_coeffs)
        expected_msg = f"Expected b_coeffs to have {filter_order + 1} elements for {filter_order}-order filter"
        assert expected_msg in str(exc_info.value), f"Expected error message to contain '{expected_msg}', got '{str(exc_info.value)}'"
        print(f"Correctly raised ValueError for short b_coeffs: {exc_info.value}")

    def test_set_coefficients_b_coeffs_too_long(self):
        """Test that ValueError is raised when b_coeffs is too long."""
        # Arrange
        filter_order = 2
        iir_filter = IIRFilter(filter_order)
        a_coeffs = [1.0, -0.5, 0.25]           # 3 elements
        b_coeffs = [0.1, 0.2, 0.1, 0.05, 0.02] # 5 elements, need 3 for order 2
        
        # Act & Assert
        with pytest.raises(ValueError) as exc_info:
            iir_filter.set_coefficients(a_coeffs, b_coeffs)
        
        expected_msg = f"Expected b_coeffs to have {filter_order + 1} elements for {filter_order}-order filter"
        assert expected_msg in str(exc_info.value), f"Expected error message to contain '{expected_msg}', got '{str(exc_info.value)}'"
        print(f"Correctly raised ValueError for long b_coeffs: {exc_info.value}")

    def test_set_coefficients_empty_lists(self):
        """Test that ValueError is raised when coefficient lists are empty."""
        # Arrange
        filter_order = 1
        iir_filter = IIRFilter(filter_order)
        a_coeffs = []  # Empty list
        b_coeffs = []  # Empty list
        
        # Act & Assert
        with pytest.raises(ValueError) as exc_info:
            iir_filter.set_coefficients(a_coeffs, b_coeffs)
        
        expected_msg = f"Expected a_coeffs to have {filter_order + 1} elements for {filter_order}-order filter, got {len(a_coeffs)}"
        assert expected_msg in str(exc_info.value), f"Expected error message to contain '{expected_msg}', got '{str(exc_info.value)}'"
        print(f"Correctly raised ValueError for empty coefficient lists: {exc_info.value}")

    def test_set_coefficients_zero_order_filter(self):
        """Test coefficient setting for zero-order filter."""
        # Arrange
        filter_order = 0
        iir_filter = IIRFilter(filter_order)
        a_coeffs = [1.0]  # 1 element for order 0
        b_coeffs = [0.5]  # 1 element for order 0
        
        # Act
        iir_filter.set_coefficients(a_coeffs, b_coeffs)
        
        # Assert
        assert iir_filter.a_coeffs == a_coeffs, f"Expected a_coeffs to be {a_coeffs}, got {iir_filter.a_coeffs}"
        assert iir_filter.b_coeffs == b_coeffs, f"Expected b_coeffs to be {b_coeffs}, got {iir_filter.b_coeffs}"
        assert len(iir_filter.a_coeffs) == 1, f"Expected a_coeffs length to be 1, got {len(iir_filter.a_coeffs)}"
        assert len(iir_filter.b_coeffs) == 1, f"Expected b_coeffs length to be 1, got {len(iir_filter.b_coeffs)}"
        print(f"Successfully configured zero-order filter: a_coeffs={iir_filter.a_coeffs}, b_coeffs={iir_filter.b_coeffs}")

    def test_set_coefficients_high_order_filter(self):
        """Test coefficient setting for high-order filter."""
        # Arrange
        filter_order = 10
        iir_filter = IIRFilter(filter_order)
        a_coeffs = [1.0] + [0.1 * i for i in range(1, 11)]  # 11 elements
        b_coeffs = [0.05 * i for i in range(1, 12)]         # 11 elements
        
        # Act
        iir_filter.set_coefficients(a_coeffs, b_coeffs)
        
        # Assert
        assert iir_filter.a_coeffs == a_coeffs, f"Expected a_coeffs to be {a_coeffs}, got {iir_filter.a_coeffs}"
        assert iir_filter.b_coeffs == b_coeffs, f"Expected b_coeffs to be {b_coeffs}, got {iir_filter.b_coeffs}"
        assert len(iir_filter.a_coeffs) == filter_order + 1, f"Expected a_coeffs length to be {filter_order + 1}, got {len(iir_filter.a_coeffs)}"
        assert len(iir_filter.b_coeffs) == filter_order + 1, f"Expected b_coeffs length to be {filter_order + 1}, got {len(iir_filter.b_coeffs)}"
        print(f"Successfully configured high-order filter with {len(a_coeffs)} coefficients each")

    def test_set_coefficients_values_preservation(self):
        """Test that coefficient values are preserved exactly including special float values."""
        # Arrange
        filter_order = 2
        iir_filter = IIRFilter(filter_order)
        a_coeffs = [1.0, -0.123456789, 1e-10]    # Includes negative and very small positive
        b_coeffs = [0.0, -1e-8, 999.999999]      # Includes zero, negative small, and large positive
        
        # Act
        iir_filter.set_coefficients(a_coeffs, b_coeffs)
        
        # Assert
        assert iir_filter.a_coeffs == a_coeffs, f"Expected a_coeffs to be {a_coeffs}, got {iir_filter.a_coeffs}"
        assert iir_filter.b_coeffs == b_coeffs, f"Expected b_coeffs to be {b_coeffs}, got {iir_filter.b_coeffs}"
        
        # Check individual values for exact preservation
        for i, (expected, actual) in enumerate(zip(a_coeffs, iir_filter.a_coeffs)):
            assert expected == actual, f"a_coeffs[{i}]: expected {expected}, got {actual}"
        
        for i, (expected, actual) in enumerate(zip(b_coeffs, iir_filter.b_coeffs)):
            assert expected == actual, f"b_coeffs[{i}]: expected {expected}, got {actual}"
        
        print(f"Successfully preserved all coefficient values exactly: a_coeffs={iir_filter.a_coeffs}, b_coeffs={iir_filter.b_coeffs}")
