# ********RoostGPT********
"""
Test generated by RoostGPT for test python-audio using AI Type Claude AI and AI Model claude-sonnet-4-20250514

ROOST_METHOD_HASH=make_bandpass_e90e9eadc4
ROOST_METHOD_SIG_HASH=make_bandpass_e90e9eadc4


Scenario 1: Standard Bandpass Filter Creation with Default Q Factor
Details:
  TestName: test_make_bandpass_with_default_q_factor
  Description: Verify that the function creates a valid bandpass filter with default Q factor (1/sqrt(2)) and returns an IIRFilter object with correctly calculated coefficients for a typical frequency and sample rate combination.
Execution:
  Arrange: Set up test parameters with frequency=1000 Hz and samplerate=48000 Hz, allowing the function to use the default Q factor.
  Act: Call make_bandpass(1000, 48000) to create the bandpass filter.
  Assert: Verify that the returned object is an IIRFilter instance with order 2, and that the a_coeffs and b_coeffs match the expected mathematical calculations for the given parameters.
Validation:
  This test ensures the core functionality works correctly with standard audio processing parameters and validates the mathematical implementation of the bandpass filter design equations.

Scenario 2: Custom Q Factor Bandpass Filter Creation
Details:
  TestName: test_make_bandpass_with_custom_q_factor
  Description: Verify that the function correctly handles custom Q factor values and produces different filter characteristics compared to the default Q factor.
Execution:
  Arrange: Set up test parameters with frequency=2000 Hz, samplerate=44100 Hz, and a custom q_factor=2.0.
  Act: Call make_bandpass(2000, 44100, 2.0) to create the bandpass filter with custom Q factor.
  Assert: Verify that the returned IIRFilter has coefficients that differ from the default Q factor case and that the coefficients are mathematically consistent with the higher Q factor (narrower bandwidth).
Validation:
  This test confirms that the Q factor parameter properly influences the filter design, which is crucial for controlling the bandwidth characteristics of the bandpass filter in audio applications.

Scenario 3: Low Frequency Bandpass Filter
Details:
  TestName: test_make_bandpass_low_frequency
  Description: Verify that the function can create bandpass filters for low frequencies without numerical instability or incorrect coefficient calculation.
Execution:
  Arrange: Set up test parameters with a low frequency=50 Hz, samplerate=48000 Hz, and default Q factor.
  Act: Call make_bandpass(50, 48000) to create a low-frequency bandpass filter.
  Assert: Verify that all coefficients are finite numbers, the filter object is properly initialized, and the coefficients reflect the low-frequency characteristics.
Validation:
  Low-frequency filters are common in audio processing for bass enhancement or rumble filtering, so ensuring stability and correctness at low frequencies is essential for practical applications.

Scenario 4: High Frequency Bandpass Filter Near Nyquist Limit
Details:
  TestName: test_make_bandpass_high_frequency
  Description: Verify that the function handles high frequencies approaching the Nyquist frequency without creating unstable or invalid filter coefficients.
Execution:
  Arrange: Set up test parameters with a high frequency=20000 Hz, samplerate=48000 Hz (frequency is close to Nyquist frequency of 24000 Hz), and default Q factor.
  Act: Call make_bandpass(20000, 48000) to create a high-frequency bandpass filter.
  Assert: Verify that the coefficients are mathematically valid, finite, and that the filter maintains stability characteristics appropriate for high-frequency operation.
Validation:
  High-frequency filters are important for treble processing and anti-aliasing applications, and the function must handle frequencies near the Nyquist limit without numerical issues.

Scenario 5: Very High Q Factor Bandpass Filter
Details:
  TestName: test_make_bandpass_very_high_q_factor
  Description: Verify that the function can create very narrow bandpass filters with high Q factors while maintaining numerical stability.
Execution:
  Arrange: Set up test parameters with frequency=1000 Hz, samplerate=48000 Hz, and a very high q_factor=10.0.
  Act: Call make_bandpass(1000, 48000, 10.0) to create a narrow bandpass filter.
  Assert: Verify that the coefficients are finite and mathematically consistent with a high Q factor design, and that the alpha calculation doesn't cause numerical issues.
Validation:
  High Q factors create very selective filters used in applications like notch filtering or precise frequency isolation, so the function must handle extreme Q values without instability.

Scenario 6: Very Low Q Factor Bandpass Filter
Details:
  TestName: test_make_bandpass_very_low_q_factor
  Description: Verify that the function correctly handles very low Q factors that create wide bandpass filters.
Execution:
  Arrange: Set up test parameters with frequency=1000 Hz, samplerate=48000 Hz, and a very low q_factor=0.1.
  Act: Call make_bandpass(1000, 48000, 0.1) to create a wide bandpass filter.
  Assert: Verify that the coefficients reflect the wide bandwidth characteristics and that the alpha calculation produces valid results for low Q factors.
Validation:
  Low Q factors create broad bandpass filters useful for general frequency shaping, and the function must handle the full range of practical Q factor values.

Scenario 7: Different Sample Rates Consistency
Details:
  TestName: test_make_bandpass_different_sample_rates
  Description: Verify that the function produces consistent relative behavior across different sample rates for the same relative frequency.
Execution:
  Arrange: Set up multiple test cases with the same relative frequency but different sample rates (e.g., 1000Hz at 44100Hz vs 2000Hz at 88200Hz).
  Act: Call make_bandpass with each parameter combination to create filters at different sample rates.
  Assert: Verify that the filters exhibit similar relative frequency response characteristics when accounting for the sample rate differences.
Validation:
  Audio applications often work with different sample rates, so the function must produce mathematically consistent results across various sample rate scenarios.

Scenario 8: Filter Coefficient Mathematical Relationships
Details:
  TestName: test_make_bandpass_coefficient_relationships
  Description: Verify that the calculated filter coefficients maintain the expected mathematical relationships defined by the bandpass filter design equations.
Execution:
  Arrange: Set up test parameters with known values that allow for easy mathematical verification.
  Act: Call make_bandpass to create a filter and extract the coefficients.
  Assert: Verify specific mathematical relationships such as b1 always being zero, b2 being the negative of b0, and the relationships between a0, a1, a2 coefficients.
Validation:
  The mathematical correctness of the filter design is fundamental to proper audio processing, and these relationships must hold for the filter to function as intended.

Scenario 9: Filter Order and Structure Validation
Details:
  TestName: test_make_bandpass_filter_structure
  Description: Verify that the returned IIRFilter object has the correct order and internal structure for a second-order bandpass filter.
Execution:
  Arrange: Set up standard test parameters for filter creation.
  Act: Call make_bandpass to create a filter and examine its structure.
  Assert: Verify that the returned filter has order=2, proper coefficient array lengths, and initialized history arrays.
Validation:
  The structural integrity of the filter object is essential for proper operation, and the function must consistently create properly structured second-order filters.

Scenario 10: Edge Case with Minimum Practical Frequency
Details:
  TestName: test_make_bandpass_minimum_frequency
  Description: Verify that the function handles very low frequencies (approaching DC) without creating invalid or unstable filter coefficients.
Execution:
  Arrange: Set up test parameters with a very low frequency=1 Hz and a high sample rate=48000 Hz.
  Act: Call make_bandpass(1, 48000) to create a very low frequency bandpass filter.
  Assert: Verify that all coefficients are finite, mathematically valid, and that the w0 calculation doesn't cause numerical precision issues.
Validation:
  Extremely low frequencies test the numerical limits of the filter design equations and ensure robustness across the full practical frequency range.

"""

# ********RoostGPT********
import pytest
from math import cos, sin, sqrt, tau, isfinite
from audio_filters.butterworth_filter import make_bandpass
from audio_filters.iir_filter import IIRFilter


class TestButterworthFilterMakeBandpass:
    
    def test_make_bandpass_with_default_q_factor(self):
        """Test standard bandpass filter creation with default Q factor"""
        # Arrange
        frequency = 1000
        samplerate = 48000
        expected_q_factor = 1 / sqrt(2)
        
        # Act
        filter_obj = make_bandpass(frequency, samplerate)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        assert filter_obj.order == 2, "Should create a second-order filter"
        
        # Calculate expected coefficients manually
        w0 = tau * frequency / samplerate
        _sin = sin(w0)
        _cos = cos(w0)
        alpha = _sin / (2 * expected_q_factor)
        
        expected_b0 = _sin / 2
        expected_b1 = 0
        expected_b2 = -expected_b0
        expected_a0 = 1 + alpha
        expected_a1 = -2 * _cos
        expected_a2 = 1 - alpha
        
        # Verify coefficients match expected values
        assert abs(filter_obj.a_coeffs[0] - expected_a0) < 1e-10, f"a0 coefficient mismatch: expected {expected_a0}, got {filter_obj.a_coeffs[0]}"
        assert abs(filter_obj.a_coeffs[1] - expected_a1) < 1e-10, f"a1 coefficient mismatch: expected {expected_a1}, got {filter_obj.a_coeffs[1]}"
        assert abs(filter_obj.a_coeffs[2] - expected_a2) < 1e-10, f"a2 coefficient mismatch: expected {expected_a2}, got {filter_obj.a_coeffs[2]}"
        assert abs(filter_obj.b_coeffs[0] - expected_b0) < 1e-10, f"b0 coefficient mismatch: expected {expected_b0}, got {filter_obj.b_coeffs[0]}"
        assert abs(filter_obj.b_coeffs[1] - expected_b1) < 1e-10, f"b1 coefficient mismatch: expected {expected_b1}, got {filter_obj.b_coeffs[1]}"
        assert abs(filter_obj.b_coeffs[2] - expected_b2) < 1e-10, f"b2 coefficient mismatch: expected {expected_b2}, got {filter_obj.b_coeffs[2]}"

    def test_make_bandpass_with_custom_q_factor(self):
        """Test bandpass filter creation with custom Q factor"""
        # Arrange
        frequency = 2000
        samplerate = 44100
        custom_q_factor = 2.0
        
        # Act
        filter_obj = make_bandpass(frequency, samplerate, custom_q_factor)
        
        # Create filter with default Q factor for comparison
        default_filter = make_bandpass(frequency, samplerate)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        assert filter_obj.order == 2, "Should create a second-order filter"
        
        # Verify coefficients are different from default Q factor
        coeffs_different = False
        for i in range(len(filter_obj.a_coeffs)):
            if abs(filter_obj.a_coeffs[i] - default_filter.a_coeffs[i]) > 1e-10:
                coeffs_different = True
                break
        
        assert coeffs_different, "Custom Q factor should produce different coefficients than default"
        
        # Verify mathematical consistency with higher Q factor
        w0 = tau * frequency / samplerate
        _sin = sin(w0)
        alpha = _sin / (2 * custom_q_factor)
        expected_a0 = 1 + alpha
        
        assert abs(filter_obj.a_coeffs[0] - expected_a0) < 1e-10, "a0 coefficient should match expected value for custom Q factor"

    def test_make_bandpass_low_frequency(self):
        """Test bandpass filter creation for low frequencies"""
        # Arrange
        frequency = 50  # Low frequency
        samplerate = 48000
        
        # Act
        filter_obj = make_bandpass(frequency, samplerate)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        
        # Verify all coefficients are finite
        for coeff in filter_obj.a_coeffs:
            assert isfinite(coeff), f"a_coeff {coeff} should be finite"
        
        for coeff in filter_obj.b_coeffs:
            assert isfinite(coeff), f"b_coeff {coeff} should be finite"
        
        # Verify filter characteristics for low frequency
        w0 = tau * frequency / samplerate
        assert w0 < 0.1, "w0 should be small for low frequency"
        
        # For low frequencies, sin(w0) ≈ w0, so b0 should be approximately w0/2
        expected_b0_approx = w0 / 2
        assert abs(filter_obj.b_coeffs[0] - expected_b0_approx) < 0.01, "b0 should approximate w0/2 for low frequencies"

    def test_make_bandpass_high_frequency(self):
        """Test bandpass filter creation for high frequencies near Nyquist limit"""
        # Arrange
        frequency = 20000  # High frequency, close to Nyquist (24000 Hz for 48kHz sample rate)
        samplerate = 48000
        
        # Act
        filter_obj = make_bandpass(frequency, samplerate)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        
        # Verify all coefficients are finite and mathematically valid
        for coeff in filter_obj.a_coeffs:
            assert isfinite(coeff), f"a_coeff {coeff} should be finite"
        
        for coeff in filter_obj.b_coeffs:
            assert isfinite(coeff), f"b_coeff {coeff} should be finite"
        
        # Verify stability - for a stable filter, |a2/a0| < 1
        stability_ratio = abs(filter_obj.a_coeffs[2] / filter_obj.a_coeffs[0])
        assert stability_ratio < 1, f"Filter should be stable: |a2/a0| = {stability_ratio} should be < 1"
        
        # Verify frequency is reasonable relative to Nyquist
        nyquist = samplerate / 2
        assert frequency < nyquist, f"Frequency {frequency} should be less than Nyquist frequency {nyquist}"

    def test_make_bandpass_very_high_q_factor(self):
        """Test bandpass filter creation with very high Q factor"""
        # Arrange
        frequency = 1000
        samplerate = 48000
        very_high_q = 10.0  # Very narrow bandpass
        
        # Act
        filter_obj = make_bandpass(frequency, samplerate, very_high_q)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        
        # Verify all coefficients are finite
        for coeff in filter_obj.a_coeffs:
            assert isfinite(coeff), f"a_coeff {coeff} should be finite for high Q"
        
        for coeff in filter_obj.b_coeffs:
            assert isfinite(coeff), f"b_coeff {coeff} should be finite for high Q"
        
        # For high Q, alpha should be small
        w0 = tau * frequency / samplerate
        _sin = sin(w0)
        alpha = _sin / (2 * very_high_q)
        assert alpha < 0.1, f"Alpha {alpha} should be small for high Q factor"
        
        # Verify mathematical consistency
        expected_a0 = 1 + alpha
        assert abs(filter_obj.a_coeffs[0] - expected_a0) < 1e-10, "a0 should match expected value for high Q"

    def test_make_bandpass_very_low_q_factor(self):
        """Test bandpass filter creation with very low Q factor"""
        # Arrange
        frequency = 1000
        samplerate = 48000
        very_low_q = 0.1  # Very wide bandpass
        
        # Act
        filter_obj = make_bandpass(frequency, samplerate, very_low_q)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        
        # Verify all coefficients are finite
        for coeff in filter_obj.a_coeffs:
            assert isfinite(coeff), f"a_coeff {coeff} should be finite for low Q"
        
        for coeff in filter_obj.b_coeffs:
            assert isfinite(coeff), f"b_coeff {coeff} should be finite for low Q"
        
        # For low Q, alpha should be large
        w0 = tau * frequency / samplerate
        _sin = sin(w0)
        alpha = _sin / (2 * very_low_q)
        assert alpha > 0.1, f"Alpha {alpha} should be large for low Q factor"
        
        # Verify mathematical consistency
        expected_a0 = 1 + alpha
        assert abs(filter_obj.a_coeffs[0] - expected_a0) < 1e-10, "a0 should match expected value for low Q"

    def test_make_bandpass_different_sample_rates(self):
        """Test bandpass filter consistency across different sample rates"""
        # Arrange
        # Same relative frequency: 1000Hz at 44100Hz vs 2000Hz at 88200Hz
        freq1, sr1 = 1000, 44100
        freq2, sr2 = 2000, 88200
        
        # Act
        filter1 = make_bandpass(freq1, sr1)
        filter2 = make_bandpass(freq2, sr2)
        
        # Assert
        # Both should have same relative frequency (w0 should be the same)
        w0_1 = tau * freq1 / sr1
        w0_2 = tau * freq2 / sr2
        
        assert abs(w0_1 - w0_2) < 1e-10, f"Relative frequencies should be equal: w0_1={w0_1}, w0_2={w0_2}"
        
        # Coefficients should be very similar for same relative frequency
        for i in range(len(filter1.a_coeffs)):
            assert abs(filter1.a_coeffs[i] - filter2.a_coeffs[i]) < 1e-10, f"a_coeffs[{i}] should be similar for same relative frequency"
        
        for i in range(len(filter1.b_coeffs)):
            assert abs(filter1.b_coeffs[i] - filter2.b_coeffs[i]) < 1e-10, f"b_coeffs[{i}] should be similar for same relative frequency"

    def test_make_bandpass_coefficient_relationships(self):
        """Test mathematical relationships between filter coefficients"""
        # Arrange
        frequency = 1500
        samplerate = 48000
        q_factor = 1.0
        
        # Act
        filter_obj = make_bandpass(frequency, samplerate, q_factor)
        
        # Assert
        # b1 should always be zero for bandpass filter
        assert filter_obj.b_coeffs[1] == 0, "b1 coefficient should always be zero for bandpass filter"
        
        # b2 should be negative of b0
        assert abs(filter_obj.b_coeffs[2] + filter_obj.b_coeffs[0]) < 1e-10, "b2 should be negative of b0"
        
        # Verify a0 > 0 (for stability)
        assert filter_obj.a_coeffs[0] > 0, "a0 should be positive for stable filter"
        
        # Verify mathematical relationships
        w0 = tau * frequency / samplerate
        _sin = sin(w0)
        _cos = cos(w0)
        alpha = _sin / (2 * q_factor)
        
        # a1 should equal -2*cos(w0)
        expected_a1 = -2 * _cos
        assert abs(filter_obj.a_coeffs[1] - expected_a1) < 1e-10, f"a1 should equal -2*cos(w0): expected {expected_a1}, got {filter_obj.a_coeffs[1]}"
        
        # a0 + a2 should equal 2 (since a0 = 1+alpha, a2 = 1-alpha)
        a0_plus_a2 = filter_obj.a_coeffs[0] + filter_obj.a_coeffs[2]
        assert abs(a0_plus_a2 - 2.0) < 1e-10, f"a0 + a2 should equal 2: got {a0_plus_a2}"

    def test_make_bandpass_filter_structure(self):
        """Test the structure and order of the returned IIRFilter object"""
        # Arrange
        frequency = 1000
        samplerate = 48000
        
        # Act
        filter_obj = make_bandpass(frequency, samplerate)
        
        # Assert
        # Verify filter order
        assert filter_obj.order == 2, "Filter should be second-order"
        
        # Verify coefficient array lengths
        assert len(filter_obj.a_coeffs) == 3, "Should have 3 a coefficients for second-order filter"
        assert len(filter_obj.b_coeffs) == 3, "Should have 3 b coefficients for second-order filter"
        
        # Verify filter object has proper structure
        assert hasattr(filter_obj, 'a_coeffs'), "Filter should have a_coeffs attribute"
        assert hasattr(filter_obj, 'b_coeffs'), "Filter should have b_coeffs attribute"
        assert hasattr(filter_obj, 'order'), "Filter should have order attribute"
        
        # Verify all coefficients are numbers
        for coeff in filter_obj.a_coeffs:
            assert isinstance(coeff, (int, float)), f"a coefficient {coeff} should be numeric"
        
        for coeff in filter_obj.b_coeffs:
            assert isinstance(coeff, (int, float)), f"b coefficient {coeff} should be numeric"

    def test_make_bandpass_minimum_frequency(self):
        """Test bandpass filter with very low frequency approaching DC"""
        # Arrange
        frequency = 1  # Very low frequency
        samplerate = 48000
        
        # Act
        filter_obj = make_bandpass(frequency, samplerate)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        
        # Verify all coefficients are finite and valid
        for coeff in filter_obj.a_coeffs:
            assert isfinite(coeff), f"a_coeff {coeff} should be finite for minimum frequency"
            assert not (coeff != coeff), f"a_coeff should not be NaN"  # NaN check
        
        for coeff in filter_obj.b_coeffs:
            assert isfinite(coeff), f"b_coeff {coeff} should be finite for minimum frequency"
            assert not (coeff != coeff), f"b_coeff should not be NaN"  # NaN check
        
        # Verify w0 calculation doesn't cause issues
        w0 = tau * frequency / samplerate
        assert w0 > 0, "w0 should be positive"
        assert w0 < 1, "w0 should be much less than 1 for very low frequencies"
        
        # For very low frequencies, coefficients should be well-behaved
        assert filter_obj.a_coeffs[0] > 0, "a0 should be positive"
        assert abs(filter_obj.a_coeffs[0] - 1.0) < 0.1, "a0 should be close to 1 for very low frequencies"

