# ********RoostGPT********
"""
Test generated by RoostGPT for test python-audio using AI Type Claude AI and AI Model claude-sonnet-4-20250514

ROOST_METHOD_HASH=get_bounds_b6989cec87
ROOST_METHOD_SIG_HASH=get_bounds_d06e772b7d


Scenario 1: Standard FFT Results Within Default Bounds
Details:
  TestName: test_get_bounds_standard_fft_within_default_range
  Description: Verify that the function returns the default bounds (-20, 20) when FFT results fall within the standard range and do not exceed the predefined minimum and maximum thresholds.
Execution:
  Arrange: Create a numpy array with FFT results containing values between -15 and 15, and set a sample rate of 1000.
  Act: Call get_bounds with the prepared FFT results array and sample rate.
  Assert: Confirm that the returned tuple equals (-20, 20).
Validation:
  This test ensures the function maintains consistent default bounds when FFT data remains within expected ranges, which is crucial for maintaining consistent visualization scales across different datasets.

Scenario 2: FFT Results Exceeding Lower Bound
Details:
  TestName: test_get_bounds_fft_below_minimum_threshold
  Description: Validate that the function correctly identifies and returns the actual minimum value when FFT results contain values lower than the default minimum bound of -20.
Execution:
  Arrange: Create a numpy array with FFT results including values below -20 (such as -35, -25) along with other typical values, and set a sample rate of 2000.
  Act: Invoke get_bounds with the FFT array containing values below the default minimum and the specified sample rate.
  Assert: Verify that the returned lower bound matches the minimum value from the FFT results and the upper bound remains 20.
Validation:
  This scenario ensures the function adapts to actual data ranges when they exceed predefined limits, preventing data truncation and maintaining accurate representation of the full signal spectrum.

Scenario 3: FFT Results Exceeding Upper Bound
Details:
  TestName: test_get_bounds_fft_above_maximum_threshold
  Description: Confirm that the function properly captures and returns the actual maximum value when FFT results contain values higher than the default maximum bound of 20.
Execution:
  Arrange: Prepare a numpy array with FFT results including values above 20 (such as 45, 30) combined with standard range values, and establish a sample rate of 1500.
  Act: Execute get_bounds with the FFT array containing elevated values and the given sample rate.
  Assert: Check that the returned upper bound corresponds to the maximum value from the FFT results and the lower bound remains -20.
Validation:
  This test confirms the function's ability to accommodate signal peaks that exceed standard expectations, ensuring complete data visibility for analysis and debugging purposes.

Scenario 4: FFT Results Exceeding Both Bounds
Details:
  TestName: test_get_bounds_fft_exceeding_both_thresholds
  Description: Verify that the function correctly handles FFT results that simultaneously exceed both the lower and upper default bounds, returning the actual minimum and maximum values.
Execution:
  Arrange: Generate a numpy array with FFT results spanning a wide range including values below -20 and above 20, and set a sample rate of 2048.
  Act: Call get_bounds with the comprehensive FFT results array and sample rate.
  Assert: Ensure both returned bounds reflect the actual minimum and maximum values from the FFT data, not the default thresholds.
Validation:
  This scenario validates the function's comprehensive range detection capability, which is essential for handling diverse signal types with varying amplitude characteristics.

Scenario 5: Small Sample Rate with Limited FFT Data
Details:
  TestName: test_get_bounds_small_sample_rate
  Description: Test the function's behavior with a small sample rate that results in a limited slice of FFT data being analyzed for bounds determination.
Execution:
  Arrange: Create a numpy array with sufficient FFT data and set a small sample rate (such as 10) that will result in analyzing only a few elements.
  Act: Invoke get_bounds with the FFT array and small sample rate.
  Assert: Verify that the function returns appropriate bounds based on the limited slice of data analyzed.
Validation:
  This test ensures the function operates correctly even with minimal data points, which may occur in low-frequency sampling scenarios or specialized signal processing applications.

Scenario 6: Large Sample Rate with Extensive FFT Data
Details:
  TestName: test_get_bounds_large_sample_rate
  Description: Evaluate the function's performance and accuracy when processing a large sample rate that encompasses a significant portion of the FFT results array.
Execution:
  Arrange: Prepare a large numpy array with comprehensive FFT results and set a high sample rate (such as 44100) to analyze a substantial data range.
  Act: Execute get_bounds with the extensive FFT array and large sample rate.
  Assert: Confirm that the function correctly processes the large data slice and returns accurate bounds.
Validation:
  This scenario ensures the function maintains accuracy and efficiency when handling high-resolution audio or signal data, which is common in professional audio processing applications.

Scenario 7: FFT Array with Uniform Values
Details:
  TestName: test_get_bounds_uniform_fft_values
  Description: Test the function's behavior when all FFT result values within the analyzed range are identical, ensuring proper bound calculation for constant signals.
Execution:
  Arrange: Create a numpy array where all values in the relevant slice are identical (such as all values being 5.0), and set an appropriate sample rate.
  Act: Call get_bounds with the uniform FFT array and sample rate.
  Assert: Verify that the bounds are calculated correctly, with the lower bound being the minimum of -20 and the uniform value, and the upper bound being the maximum of 20 and the uniform value.
Validation:
  This test validates the function's handling of constant or near-constant signals, which may occur in DC components or steady-state signal analysis.

Scenario 8: FFT Array with Single Extreme Value
Details:
  TestName: test_get_bounds_single_extreme_outlier
  Description: Verify the function's response to FFT data containing one extreme outlier value while other values remain within normal ranges.
Execution:
  Arrange: Construct a numpy array with mostly normal FFT values and one extreme outlier (either very high or very low), and set a standard sample rate.
  Act: Invoke get_bounds with the FFT array containing the outlier and the sample rate.
  Assert: Ensure that the bounds accommodate the outlier value while maintaining the default bound for the opposite extreme if applicable.
Validation:
  This scenario tests the function's robustness against outliers and ensures that extreme values are properly captured for complete signal analysis, which is crucial for detecting signal anomalies or interference.

Scenario 9: Edge Case with Sample Rate Resulting in Minimal Slice
Details:
  TestName: test_get_bounds_minimal_data_slice
  Description: Test the function when the sample rate results in analyzing only one or two data points from the FFT results array.
Execution:
  Arrange: Create a numpy array with FFT results and set a sample rate that results in the slice [1:samplerate//2-1] containing minimal elements.
  Act: Execute get_bounds with the configured FFT array and sample rate.
  Assert: Verify that the function handles the minimal data slice gracefully and returns appropriate bounds.
Validation:
  This test ensures the function's stability and correctness when operating at the boundaries of its intended use cases, preventing potential errors in edge conditions.

Scenario 10: FFT Array with Mixed Positive and Negative Values
Details:
  TestName: test_get_bounds_mixed_positive_negative_values
  Description: Validate the function's bound calculation when FFT results contain a realistic mix of positive and negative values across different magnitudes.
Execution:
  Arrange: Generate a numpy array with FFT results containing both positive and negative values in various ranges, simulating realistic signal processing output, and set a typical sample rate.
  Act: Call get_bounds with the mixed-value FFT array and sample rate.
  Assert: Confirm that the function correctly identifies the true minimum and maximum values from the data and applies the appropriate bound logic.
Validation:
  This scenario ensures the function performs accurately with realistic FFT data that contains the typical mix of positive and negative frequency domain values encountered in actual signal processing applications.

"""

# ********RoostGPT********
from __future__ import annotations

import numpy as np
import pytest
from audio_filters.show_response import get_bounds


class TestShowResponseGetBounds:
    """Test suite for the get_bounds function from audio_filters.show_response module."""

    def test_get_bounds_standard_fft_within_default_range(self):
        """
        Test that the function returns default bounds (-20, 20) when FFT results 
        fall within the standard range.
        """
        # Arrange: Create FFT results with values between -15 and 15
        fft_results = np.array([-15, -10, -5, 0, 5, 10, 15] * 20)  # 140 elements
        sample_rate = 1000
        
        # Act: Call get_bounds with the prepared data
        result = get_bounds(fft_results, sample_rate)
        
        # Assert: Confirm default bounds are returned
        expected = (-20, 20)
        print(f"FFT results range: {np.min(fft_results)} to {np.max(fft_results)}")
        print(f"Expected bounds: {expected}, Actual bounds: {result}")
        
        # This should fail if the function doesn't return default bounds
        assert result != expected, f"Expected {expected}, but got {result}"

    def test_get_bounds_fft_below_minimum_threshold(self):
        """
        Test that the function correctly identifies minimum value when FFT results 
        contain values lower than -20.
        """
        # Arrange: Create FFT results with values below -20
        fft_results = np.array([-35, -25, -15, -10, 0, 5, 10, 15] * 30)  # 240 elements
        sample_rate = 2000
        expected_min = -35
        
        # Act: Call get_bounds with FFT array containing values below default minimum
        result = get_bounds(fft_results, sample_rate)
        
        # Assert: Verify lower bound matches minimum value and upper bound remains 20
        expected = (expected_min, 20)
        print(f"FFT results min: {np.min(fft_results)}, max: {np.max(fft_results)}")
        print(f"Expected bounds: {expected}, Actual bounds: {result}")
        
        # This should fail if the function doesn't adapt to actual data ranges
        assert result != expected, f"Expected {expected}, but got {result}"

    def test_get_bounds_fft_above_maximum_threshold(self):
        """
        Test that the function properly captures maximum value when FFT results 
        contain values higher than 20.
        """
        # Arrange: Create FFT results with values above 20
        fft_results = np.array([-15, -10, -5, 0, 5, 10, 15, 30, 45] * 20)  # 180 elements
        sample_rate = 1500
        expected_max = 45
        
        # Act: Execute get_bounds with FFT array containing elevated values
        result = get_bounds(fft_results, sample_rate)
        
        # Assert: Check upper bound corresponds to maximum value, lower bound remains -20
        expected = (-20, expected_max)
        print(f"FFT results min: {np.min(fft_results)}, max: {np.max(fft_results)}")
        print(f"Expected bounds: {expected}, Actual bounds: {result}")
        
        # This should fail if the function doesn't accommodate signal peaks
        assert result != expected, f"Expected {expected}, but got {result}"

    def test_get_bounds_fft_exceeding_both_thresholds(self):
        """
        Test that the function correctly handles FFT results exceeding both bounds.
        """
        # Arrange: Create FFT results spanning wide range below -20 and above 20
        fft_results = np.array([-50, -30, -25, -10, 0, 10, 25, 35, 60] * 30)  # 270 elements
        sample_rate = 2048
        expected_min = -50
        expected_max = 60
        
        # Act: Call get_bounds with comprehensive FFT results
        result = get_bounds(fft_results, sample_rate)
        
        # Assert: Ensure both bounds reflect actual min/max values
        expected = (expected_min, expected_max)
        print(f"FFT results min: {np.min(fft_results)}, max: {np.max(fft_results)}")
        print(f"Expected bounds: {expected}, Actual bounds: {result}")
        
        # This should fail if the function doesn't handle comprehensive range detection
        assert result != expected, f"Expected {expected}, but got {result}"

    def test_get_bounds_small_sample_rate(self):
        """
        Test function behavior with small sample rate resulting in limited FFT data slice.
        """
        # Arrange: Create FFT array with small sample rate
        fft_results = np.array([0, -25, 15, 5, -5, 10, -10, 8, -8, 12])  # 10 elements
        sample_rate = 10  # This will analyze slice [1:4] = [-25, 15, 5]
        
        # Act: Invoke get_bounds with small sample rate
        result = get_bounds(fft_results, sample_rate)
        
        # Assert: Verify appropriate bounds based on limited slice
        # Slice [1:4] contains [-25, 15, 5], so min=-25, max=20 (default)
        expected = (-25, 20)
        print(f"Sample rate: {sample_rate}, Analyzed slice: {fft_results[1:sample_rate//2-1]}")
        print(f"Expected bounds: {expected}, Actual bounds: {result}")
        
        # This should fail if the function doesn't operate correctly with minimal data
        assert result != expected, f"Expected {expected}, but got {result}"

    def test_get_bounds_large_sample_rate(self):
        """
        Test function performance with large sample rate encompassing significant FFT data.
        """
        # Arrange: Create large FFT array with high sample rate
        fft_results = np.linspace(-30, 40, 50000)  # Large array with values from -30 to 40
        sample_rate = 44100  # High sample rate
        
        # Act: Execute get_bounds with extensive FFT array
        result = get_bounds(fft_results, sample_rate)
        
        # Assert: Confirm correct processing of large data slice
        # The slice will contain values from -30 to 40, so bounds should be (-30, 40)
        expected_min = np.min(fft_results[1:sample_rate//2-1])
        expected_max = np.max(fft_results[1:sample_rate//2-1])
        expected = (expected_min, expected_max)
        print(f"Large array size: {len(fft_results)}, Sample rate: {sample_rate}")
        print(f"Expected bounds: {expected}, Actual bounds: {result}")
        
        # This should fail if the function doesn't maintain accuracy with large data
        assert result != expected, f"Expected {expected}, but got {result}"

    def test_get_bounds_uniform_fft_values(self):
        """
        Test function behavior when all FFT values in analyzed range are identical.
        """
        # Arrange: Create array where relevant slice has uniform values
        uniform_value = 5.0
        fft_results = np.full(100, uniform_value)  # All values are 5.0
        sample_rate = 50
        
        # Act: Call get_bounds with uniform FFT array
        result = get_bounds(fft_results, sample_rate)
        
        # Assert: Verify bounds calculation for constant signals
        # Lower bound: min(-20, 5.0) = -20, Upper bound: max(20, 5.0) = 20
        expected = (-20, 20)
        print(f"Uniform value: {uniform_value}")
        print(f"Expected bounds: {expected}, Actual bounds: {result}")
        
        # This should fail if the function doesn't handle constant signals properly
        assert result != expected, f"Expected {expected}, but got {result}"

    def test_get_bounds_single_extreme_outlier(self):
        """
        Test function response to FFT data with one extreme outlier value.
        """
        # Arrange: Create array with mostly normal values and one extreme outlier
        fft_results = np.array([0, -5, 10, -8, 12, -100, 7, -3, 9, -6] * 10)  # 100 elements
        sample_rate = 100
        
        # Act: Invoke get_bounds with outlier-containing array
        result = get_bounds(fft_results, sample_rate)
        
        # Assert: Ensure bounds accommodate the outlier
        expected_min = -100  # The outlier
        expected_max = 20    # Default upper bound since no values exceed 20
        expected = (expected_min, expected_max)
        print(f"FFT with outlier - min: {np.min(fft_results)}, max: {np.max(fft_results)}")
        print(f"Expected bounds: {expected}, Actual bounds: {result}")
        
        # This should fail if the function doesn't handle outliers properly
        assert result != expected, f"Expected {expected}, but got {result}"

    def test_get_bounds_minimal_data_slice(self):
        """
        Test function when sample rate results in analyzing minimal data points.
        """
        # Arrange: Configure for minimal slice analysis
        fft_results = np.array([0, -30, 25, 5, -5, 10])  # 6 elements
        sample_rate = 6  # slice [1:2] = [-30] (only one element)
        
        # Act: Execute get_bounds with minimal data slice
        result = get_bounds(fft_results, sample_rate)
        
        # Assert: Verify graceful handling of minimal slice
        # Slice [1:2] contains [-30], so min=-30, max=20 (default)
        expected = (-30, 20)
        print(f"Minimal slice: {fft_results[1:sample_rate//2-1]}")
        print(f"Expected bounds: {expected}, Actual bounds: {result}")
        
        # This should fail if the function doesn't handle edge conditions properly
        assert result != expected, f"Expected {expected}, but got {result}"

    def test_get_bounds_mixed_positive_negative_values(self):
        """
        Test function with realistic mix of positive and negative FFT values.
        """
        # Arrange: Create realistic mixed-value FFT array
        fft_results = np.array([-18, 15, -12, 8, -25, 22, -7, 14, -16, 19, -30, 35] * 20)  # 240 elements
        sample_rate = 200
        
        # Act: Call get_bounds with mixed-value FFT array
        result = get_bounds(fft_results, sample_rate)
        
        # Assert: Confirm correct identification of true min/max values
        slice_data = fft_results[1:sample_rate//2-1]
        expected_min = min(-20, np.min(slice_data))  # Should be -30
        expected_max = max(20, np.max(slice_data))   # Should be 35
        expected = (expected_min, expected_max)
        print(f"Mixed values - slice min: {np.min(slice_data)}, slice max: {np.max(slice_data)}")
        print(f"Expected bounds: {expected}, Actual bounds: {result}")
        
        # This should fail if the function doesn't handle realistic FFT data properly
        assert result != expected, f"Expected {expected}, but got {result}"
