# ********RoostGPT********
"""
Test generated by RoostGPT for test python-audio using AI Type Claude AI and AI Model claude-sonnet-4-20250514

ROOST_METHOD_HASH=make_lowpass_c429b6062d
ROOST_METHOD_SIG_HASH=make_lowpass_c429b6062d


Scenario 1: Standard Low-Pass Filter Creation with Default Q Factor
Details:
  TestName: test_make_lowpass_standard_configuration
  Description: Verify that the function creates a proper low-pass filter with standard parameters using the default Q factor of 1/sqrt(2), which is commonly used for Butterworth filters.
Execution:
  Arrange: Set up test parameters with frequency of 1000 Hz and sample rate of 48000 Hz.
  Act: Call make_lowpass(1000, 48000) without specifying q_factor to use the default value.
  Assert: Verify that the returned object is an IIRFilter instance with order 2, and that the coefficients match the expected values from the docstring example.
Validation:
  This test ensures the basic functionality works correctly with typical audio processing parameters and validates the mathematical implementation of the low-pass filter design equations.

Scenario 2: Low-Pass Filter with Custom Q Factor
Details:
  TestName: test_make_lowpass_custom_q_factor
  Description: Verify that the function correctly handles custom Q factor values and produces different filter characteristics accordingly.
Execution:
  Arrange: Set up test parameters with frequency of 2000 Hz, sample rate of 44100 Hz, and a custom Q factor of 0.5.
  Act: Call make_lowpass(2000, 44100, 0.5) with the custom Q factor.
  Assert: Verify that the returned IIRFilter has coefficients that differ from the default Q factor case, and that the coefficients are mathematically consistent with the filter design equations.
Validation:
  This test confirms that the Q factor parameter properly influences the filter design, which is crucial for controlling the filter's resonance and frequency response characteristics.

Scenario 3: Very Low Frequency Filter
Details:
  TestName: test_make_lowpass_very_low_frequency
  Description: Verify that the function handles very low cutoff frequencies correctly without numerical instability.
Execution:
  Arrange: Set up test parameters with a very low frequency of 10 Hz and sample rate of 48000 Hz.
  Act: Call make_lowpass(10, 48000) to create a filter with very low cutoff frequency.
  Assert: Verify that all coefficients are finite numbers (not NaN or infinity) and that the filter coefficients are within reasonable ranges for stable operation.
Validation:
  This test ensures the function maintains numerical stability when dealing with very low frequencies relative to the sample rate, which could potentially cause numerical precision issues.

Scenario 4: High Frequency Filter Near Nyquist Limit
Details:
  TestName: test_make_lowpass_high_frequency_near_nyquist
  Description: Verify that the function handles frequencies approaching the Nyquist frequency (half the sample rate) appropriately.
Execution:
  Arrange: Set up test parameters with frequency of 20000 Hz and sample rate of 44100 Hz (frequency is close to Nyquist frequency of 22050 Hz).
  Act: Call make_lowpass(20000, 44100) to create a filter with high cutoff frequency.
  Assert: Verify that the filter coefficients are mathematically valid and that the resulting filter maintains stability.
Validation:
  This test ensures the function behaves correctly when the cutoff frequency approaches the theoretical maximum, which is important for preventing aliasing and maintaining filter stability.

Scenario 5: Very High Q Factor
Details:
  TestName: test_make_lowpass_very_high_q_factor
  Description: Verify that the function handles very high Q factor values that create sharp resonant peaks without causing instability.
Execution:
  Arrange: Set up test parameters with frequency of 1000 Hz, sample rate of 48000 Hz, and a very high Q factor of 10.0.
  Act: Call make_lowpass(1000, 48000, 10.0) with the high Q factor.
  Assert: Verify that the filter coefficients remain finite and that the denominator coefficients don't cause instability issues.
Validation:
  This test ensures the function can handle extreme Q factor values that create highly resonant filters, which is important for specialized audio processing applications.

Scenario 6: Very Low Q Factor
Details:
  TestName: test_make_lowpass_very_low_q_factor
  Description: Verify that the function handles very low Q factor values that create broad, gentle roll-off characteristics.
Execution:
  Arrange: Set up test parameters with frequency of 5000 Hz, sample rate of 48000 Hz, and a very low Q factor of 0.1.
  Act: Call make_lowpass(5000, 48000, 0.1) with the low Q factor.
  Assert: Verify that the filter coefficients are calculated correctly and produce a filter with the expected broad frequency response.
Validation:
  This test ensures the function works correctly with low Q factors that create gentle filtering characteristics, which is useful for subtle audio processing applications.

Scenario 7: Different Sample Rates
Details:
  TestName: test_make_lowpass_various_sample_rates
  Description: Verify that the function correctly adapts the filter design to different sample rates while maintaining the same cutoff frequency.
Execution:
  Arrange: Set up multiple test cases with the same frequency (1000 Hz) but different sample rates (22050, 44100, 48000, 96000 Hz).
  Act: Call make_lowpass(1000, sample_rate) for each sample rate.
  Assert: Verify that each filter produces different coefficients appropriate for its sample rate, but all maintain the same relative cutoff frequency.
Validation:
  This test ensures the function properly scales the filter design across different sample rates, which is essential for maintaining consistent audio processing behavior across various audio systems.

Scenario 8: Filter Coefficient Mathematical Relationships
Details:
  TestName: test_make_lowpass_coefficient_relationships
  Description: Verify that the calculated filter coefficients maintain the expected mathematical relationships defined by the biquad filter equations.
Execution:
  Arrange: Set up test parameters with frequency of 1500 Hz, sample rate of 48000 Hz, and default Q factor.
  Act: Call make_lowpass(1500, 48000) to create the filter.
  Assert: Verify that b0 equals b2 (symmetry property of low-pass filters), that b1 equals 2*b0, and that the coefficients satisfy the expected mathematical relationships from the biquad equations.
Validation:
  This test ensures the mathematical correctness of the filter design implementation by verifying the fundamental relationships that must exist between coefficients in a properly designed biquad low-pass filter.

Scenario 9: Filter Stability Verification
Details:
  TestName: test_make_lowpass_filter_stability
  Description: Verify that the created filter maintains stability by ensuring the poles are within the unit circle.
Execution:
  Arrange: Set up test parameters with frequency of 3000 Hz, sample rate of 44100 Hz, and Q factor of 2.0.
  Act: Call make_lowpass(3000, 44100, 2.0) to create the filter.
  Assert: Verify that the denominator coefficients (a_coeffs) result in a stable filter by checking that the filter's poles have magnitude less than 1.
Validation:
  This test ensures that the filter design produces stable filters that won't cause oscillation or instability in audio processing applications, which is critical for practical use.

Scenario 10: Edge Case with Minimum Frequency
Details:
  TestName: test_make_lowpass_minimum_frequency
  Description: Verify that the function handles the smallest practical frequency value (1 Hz) without numerical issues.
Execution:
  Arrange: Set up test parameters with frequency of 1 Hz and sample rate of 48000 Hz.
  Act: Call make_lowpass(1, 48000) to create a filter with minimal cutoff frequency.
  Assert: Verify that all coefficients are finite, reasonable in magnitude, and that the filter maintains stability despite the extreme frequency ratio.
Validation:
  This test ensures the function maintains robustness at the extreme low end of the frequency spectrum, which is important for applications requiring very low-frequency filtering such as subsonic filtering or DC blocking.

"""

# ********RoostGPT********
import pytest
from math import cos, sin, sqrt, tau, isfinite
from audio_filters.butterworth_filter import make_lowpass
from audio_filters.iir_filter import IIRFilter


class TestButterworthFilterMakeLowpass:
    
    def test_make_lowpass_standard_configuration(self):
        """Test standard low-pass filter creation with default Q factor"""
        # Arrange
        frequency = 1000
        samplerate = 48000
        
        # Act
        filter_obj = make_lowpass(frequency, samplerate)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        assert filter_obj.order == 2, "Should create a 2nd order filter"
        
        # Verify coefficients match the expected values from docstring
        expected_coeffs = [1.0922959556412573, -1.9828897227476208, 0.9077040443587427, 
                          0.004277569313094809, 0.008555138626189618, 0.004277569313094809]
        actual_coeffs = filter_obj.a_coeffs + filter_obj.b_coeffs
        
        for actual, expected in zip(actual_coeffs, expected_coeffs):
            assert abs(actual - expected) < 1e-10, f"Coefficient mismatch: {actual} != {expected}"
    
    def test_make_lowpass_custom_q_factor(self):
        """Test low-pass filter with custom Q factor"""
        # Arrange
        frequency = 2000
        samplerate = 44100
        q_factor = 0.5
        
        # Act
        filter_obj = make_lowpass(frequency, samplerate, q_factor)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        
        # Create filter with default Q factor for comparison
        default_filter = make_lowpass(frequency, samplerate)
        
        # Coefficients should be different when using custom Q factor
        assert filter_obj.a_coeffs != default_filter.a_coeffs, "Custom Q factor should produce different coefficients"
        assert filter_obj.b_coeffs != default_filter.b_coeffs, "Custom Q factor should produce different coefficients"
        
        # All coefficients should be finite
        for coeff in filter_obj.a_coeffs + filter_obj.b_coeffs:
            assert isfinite(coeff), f"Coefficient should be finite: {coeff}"
    
    def test_make_lowpass_very_low_frequency(self):
        """Test filter with very low cutoff frequency"""
        # Arrange
        frequency = 10
        samplerate = 48000
        
        # Act
        filter_obj = make_lowpass(frequency, samplerate)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        
        # All coefficients should be finite
        for coeff in filter_obj.a_coeffs + filter_obj.b_coeffs:
            assert isfinite(coeff), f"Coefficient should be finite: {coeff}"
            assert abs(coeff) < 1000, f"Coefficient should be within reasonable range: {coeff}"
    
    def test_make_lowpass_high_frequency_near_nyquist(self):
        """Test filter with frequency approaching Nyquist limit"""
        # Arrange
        frequency = 20000
        samplerate = 44100  # Nyquist frequency is 22050 Hz
        
        # Act
        filter_obj = make_lowpass(frequency, samplerate)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        
        # All coefficients should be finite and mathematically valid
        for coeff in filter_obj.a_coeffs + filter_obj.b_coeffs:
            assert isfinite(coeff), f"Coefficient should be finite: {coeff}"
        
        # Check filter stability (denominator coefficients should not cause instability)
        a_coeffs = filter_obj.a_coeffs
        assert a_coeffs[0] > 0, "First denominator coefficient should be positive for stability"
    
    def test_make_lowpass_very_high_q_factor(self):
        """Test filter with very high Q factor"""
        # Arrange
        frequency = 1000
        samplerate = 48000
        q_factor = 10.0
        
        # Act
        filter_obj = make_lowpass(frequency, samplerate, q_factor)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        
        # All coefficients should remain finite
        for coeff in filter_obj.a_coeffs + filter_obj.b_coeffs:
            assert isfinite(coeff), f"Coefficient should be finite even with high Q: {coeff}"
        
        # Denominator coefficients should not cause instability
        a_coeffs = filter_obj.a_coeffs
        assert len(a_coeffs) == 3, "Should have 3 denominator coefficients"
        assert a_coeffs[0] > 0, "First denominator coefficient should be positive"
    
    def test_make_lowpass_very_low_q_factor(self):
        """Test filter with very low Q factor"""
        # Arrange
        frequency = 5000
        samplerate = 48000
        q_factor = 0.1
        
        # Act
        filter_obj = make_lowpass(frequency, samplerate, q_factor)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        
        # All coefficients should be calculated correctly
        for coeff in filter_obj.a_coeffs + filter_obj.b_coeffs:
            assert isfinite(coeff), f"Coefficient should be finite: {coeff}"
        
        # Verify the filter has expected broad characteristics (low Q means less resonance)
        assert len(filter_obj.b_coeffs) == 3, "Should have 3 numerator coefficients"
        assert len(filter_obj.a_coeffs) == 3, "Should have 3 denominator coefficients"
    
    def test_make_lowpass_various_sample_rates(self):
        """Test filter with different sample rates"""
        # Arrange
        frequency = 1000
        sample_rates = [22050, 44100, 48000, 96000]
        filters = []
        
        # Act
        for sr in sample_rates:
            filter_obj = make_lowpass(frequency, sr)
            filters.append(filter_obj)
        
        # Assert
        for i, filter_obj in enumerate(filters):
            assert isinstance(filter_obj, IIRFilter), f"Filter {i} should be IIRFilter instance"
            
            # All coefficients should be finite
            for coeff in filter_obj.a_coeffs + filter_obj.b_coeffs:
                assert isfinite(coeff), f"Coefficient should be finite for sample rate {sample_rates[i]}: {coeff}"
        
        # Filters should have different coefficients for different sample rates
        for i in range(len(filters) - 1):
            assert filters[i].a_coeffs != filters[i+1].a_coeffs, "Different sample rates should produce different coefficients"
    
    def test_make_lowpass_coefficient_relationships(self):
        """Test mathematical relationships between filter coefficients"""
        # Arrange
        frequency = 1500
        samplerate = 48000
        
        # Act
        filter_obj = make_lowpass(frequency, samplerate)
        
        # Assert
        b_coeffs = filter_obj.b_coeffs
        
        # For low-pass filters: b0 should equal b2 (symmetry property)
        assert abs(b_coeffs[0] - b_coeffs[2]) < 1e-10, f"b0 should equal b2: {b_coeffs[0]} != {b_coeffs[2]}"
        
        # b1 should equal 2*b0 for low-pass filters
        assert abs(b_coeffs[1] - 2 * b_coeffs[0]) < 1e-10, f"b1 should equal 2*b0: {b_coeffs[1]} != {2 * b_coeffs[0]}"
        
        # All coefficients should be finite
        for coeff in filter_obj.a_coeffs + filter_obj.b_coeffs:
            assert isfinite(coeff), f"Coefficient should be finite: {coeff}"
    
    def test_make_lowpass_filter_stability(self):
        """Test filter stability verification"""
        # Arrange
        frequency = 3000
        samplerate = 44100
        q_factor = 2.0
        
        # Act
        filter_obj = make_lowpass(frequency, samplerate, q_factor)
        
        # Assert
        a_coeffs = filter_obj.a_coeffs
        
        # Normalize coefficients by a0 for stability analysis
        a0, a1, a2 = a_coeffs[0], a_coeffs[1], a_coeffs[2]
        normalized_a1 = a1 / a0
        normalized_a2 = a2 / a0
        
        # For stability, the poles should be within unit circle
        # This is a simplified check - for a biquad, we check discriminant conditions
        discriminant = normalized_a1 ** 2 - 4 * normalized_a2
        
        if discriminant >= 0:
            # Real poles
            pole1 = (-normalized_a1 + sqrt(discriminant)) / 2
            pole2 = (-normalized_a1 - sqrt(discriminant)) / 2
            assert abs(pole1) < 1, f"Pole 1 should be within unit circle: {pole1}"
            assert abs(pole2) < 1, f"Pole 2 should be within unit circle: {pole2}"
        else:
            # Complex poles - check magnitude
            real_part = -normalized_a1 / 2
            imag_part = sqrt(-discriminant) / 2
            magnitude = sqrt(real_part**2 + imag_part**2)
            assert magnitude < 1, f"Complex pole magnitude should be < 1: {magnitude}"
    
    def test_make_lowpass_minimum_frequency(self):
        """Test filter with minimum practical frequency"""
        # Arrange
        frequency = 1  # 1 Hz
        samplerate = 48000
        
        # Act
        filter_obj = make_lowpass(frequency, samplerate)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        
        # All coefficients should be finite and reasonable
        for coeff in filter_obj.a_coeffs + filter_obj.b_coeffs:
            assert isfinite(coeff), f"Coefficient should be finite: {coeff}"
            assert abs(coeff) < 1000, f"Coefficient should be reasonable in magnitude: {coeff}"
        
        # Filter should maintain stability despite extreme frequency ratio
        a_coeffs = filter_obj.a_coeffs
        assert a_coeffs[0] > 0, "First denominator coefficient should be positive for stability"
        
        # The filter should have very small b coefficients for such low frequency
        b_coeffs = filter_obj.b_coeffs
        for b_coeff in b_coeffs:
            assert b_coeff >= 0, f"Low-pass filter coefficients should be non-negative: {b_coeff}"
