# ********RoostGPT********
"""
Test generated by RoostGPT for test python-audio using AI Type Claude AI and AI Model claude-sonnet-4-20250514

ROOST_METHOD_HASH=make_allpass_aa18b576e9
ROOST_METHOD_SIG_HASH=make_allpass_aa18b576e9


Scenario 1: Standard All-Pass Filter Creation with Default Q Factor
Details:
  TestName: test_make_allpass_with_default_q_factor
  Description: Verify that the function creates a valid all-pass filter with default Q factor (1/sqrt(2)) and returns an IIRFilter instance with correctly calculated coefficients.
Execution:
  Arrange: Define standard test parameters with frequency of 1000 Hz and sample rate of 48000 Hz.
  Act: Call make_allpass(1000, 48000) without specifying q_factor parameter.
  Assert: Verify that the returned object is an IIRFilter instance with order 2, and that the coefficients match the expected mathematical calculation for an all-pass filter.
Validation:
  This test ensures the core functionality works correctly with the most common usage pattern, validating the mathematical implementation of the all-pass filter design equations.

Scenario 2: All-Pass Filter Creation with Custom Q Factor
Details:
  TestName: test_make_allpass_with_custom_q_factor
  Description: Verify that the function correctly handles custom Q factor values and produces appropriate coefficient variations.
Execution:
  Arrange: Set up test parameters with frequency of 2000 Hz, sample rate of 44100 Hz, and custom Q factor of 0.5.
  Act: Call make_allpass(2000, 44100, 0.5) with the custom Q factor.
  Assert: Confirm that the returned IIRFilter has coefficients that differ from the default Q factor case and that the mathematical relationships between a and b coefficients are maintained.
Validation:
  This test validates that the Q factor parameter correctly influences the filter characteristics and that the function can handle various Q factor values as expected in audio processing applications.

Scenario 3: Low Frequency All-Pass Filter
Details:
  TestName: test_make_allpass_low_frequency
  Description: Verify the function's behavior when creating an all-pass filter for very low frequencies relative to the sample rate.
Execution:
  Arrange: Configure parameters with a low frequency of 50 Hz and high sample rate of 48000 Hz.
  Act: Call make_allpass(50, 48000) to create a low-frequency all-pass filter.
  Assert: Ensure the returned filter has valid coefficients and that the mathematical calculations remain stable for small w0 values.
Validation:
  This test ensures the function maintains numerical stability and produces valid results when the frequency is much smaller than the Nyquist frequency, which is common in bass processing applications.

Scenario 4: High Frequency All-Pass Filter Near Nyquist Limit
Details:
  TestName: test_make_allpass_high_frequency_near_nyquist
  Description: Verify the function's behavior when creating an all-pass filter for frequencies approaching the Nyquist limit.
Execution:
  Arrange: Set parameters with a high frequency of 20000 Hz and sample rate of 44100 Hz (approaching Nyquist frequency of 22050 Hz).
  Act: Call make_allpass(20000, 44100) to create a high-frequency all-pass filter.
  Assert: Verify that the returned filter has mathematically valid coefficients and that the calculations remain stable near the Nyquist limit.
Validation:
  This test ensures the function handles edge cases near the theoretical frequency limits without producing invalid or unstable filter coefficients, which is crucial for high-frequency audio processing.

Scenario 5: All-Pass Filter with Very High Q Factor
Details:
  TestName: test_make_allpass_very_high_q_factor
  Description: Verify the function's behavior when using a very high Q factor value that creates a narrow resonance.
Execution:
  Arrange: Configure parameters with frequency of 1000 Hz, sample rate of 48000 Hz, and high Q factor of 10.0.
  Act: Call make_allpass(1000, 48000, 10.0) with the high Q factor.
  Assert: Confirm that the returned filter has valid coefficients and that the high Q factor appropriately affects the alpha calculation and resulting coefficients.
Validation:
  This test validates that the function can handle high Q factor values that create sharp resonances, ensuring the mathematical implementation remains stable for extreme parameter values used in specialized audio effects.

Scenario 6: All-Pass Filter with Very Low Q Factor
Details:
  TestName: test_make_allpass_very_low_q_factor
  Description: Verify the function's behavior when using a very low Q factor value that creates a broad resonance.
Execution:
  Arrange: Set parameters with frequency of 1500 Hz, sample rate of 48000 Hz, and low Q factor of 0.1.
  Act: Call make_allpass(1500, 48000, 0.1) with the low Q factor.
  Assert: Ensure the returned filter has mathematically consistent coefficients and that the low Q factor produces the expected broad resonance characteristics.
Validation:
  This test ensures the function handles low Q factor values correctly, which is important for creating subtle phase effects and broad resonances in audio processing applications.

Scenario 7: All-Pass Filter Coefficient Symmetry Verification
Details:
  TestName: test_make_allpass_coefficient_symmetry
  Description: Verify that the all-pass filter maintains the characteristic symmetry between numerator and denominator coefficients.
Execution:
  Arrange: Create an all-pass filter with frequency of 800 Hz and sample rate of 48000 Hz.
  Act: Call make_allpass(800, 48000) and extract the a_coeffs and b_coeffs from the returned filter.
  Assert: Verify that b_coeffs[0] equals a_coeffs[2], b_coeffs[1] equals a_coeffs[1], and b_coeffs[2] equals a_coeffs[0], confirming the mathematical symmetry property of all-pass filters.
Validation:
  This test validates the fundamental mathematical property of all-pass filters where the numerator coefficients are the reverse of the denominator coefficients, ensuring the filter maintains unity magnitude response across all frequencies.

Scenario 8: All-Pass Filter with Different Sample Rates
Details:
  TestName: test_make_allpass_different_sample_rates
  Description: Verify that the function produces different but mathematically consistent results when the same frequency is used with different sample rates.
Execution:
  Arrange: Prepare two sets of parameters with the same frequency (1000 Hz) but different sample rates (44100 Hz and 96000 Hz).
  Act: Call make_allpass(1000, 44100) and make_allpass(1000, 96000) to create filters with different sample rates.
  Assert: Confirm that both filters have valid coefficients but with different values, and that the relationship between frequency and sample rate is correctly reflected in the coefficient calculations.
Validation:
  This test ensures that the function correctly adapts the filter design to different sample rates while maintaining the same target frequency, which is essential for audio applications that work with various sample rates.

Scenario 9: All-Pass Filter Mathematical Consistency Check
Details:
  TestName: test_make_allpass_mathematical_consistency
  Description: Verify that the calculated coefficients follow the expected mathematical relationships derived from the all-pass filter design equations.
Execution:
  Arrange: Set up parameters with frequency of 1200 Hz, sample rate of 48000 Hz, and Q factor of 0.8.
  Act: Call make_allpass(1200, 48000, 0.8) and extract the coefficients.
  Assert: Verify that the coefficients satisfy the mathematical relationships: b0 = 1 - alpha, b1 = -2*cos(w0), b2 = 1 + alpha, and that these match the denominator coefficients in reverse order.
Validation:
  This test validates the mathematical correctness of the coefficient calculations, ensuring that the implementation accurately follows the theoretical all-pass filter design formulas used in digital signal processing.

Scenario 10: All-Pass Filter Return Type and Structure Validation
Details:
  TestName: test_make_allpass_return_type_and_structure
  Description: Verify that the function returns a properly configured IIRFilter instance with the correct order and coefficient structure.
Execution:
  Arrange: Define standard parameters with frequency of 1000 Hz and sample rate of 48000 Hz.
  Act: Call make_allpass(1000, 48000) and examine the returned object's properties.
  Assert: Confirm that the returned object is an instance of IIRFilter, has order 2, contains 3 elements each in a_coeffs and b_coeffs lists, and has properly initialized input and output history arrays.
Validation:
  This test ensures that the function correctly integrates with the IIRFilter class and returns a fully functional filter object that can be immediately used for audio processing without additional configuration.

"""

# ********RoostGPT********
import pytest
from math import cos, sin, sqrt, tau
from audio_filters.iir_filter import IIRFilter
from audio_filters.butterworth_filter import make_allpass


class TestButterworthFilterMakeAllpass:
    
    def test_make_allpass_with_default_q_factor(self):
        """Test all-pass filter creation with default Q factor (1/sqrt(2))"""
        # Arrange
        frequency = 1000
        samplerate = 48000
        expected_q_factor = 1 / sqrt(2)
        
        # Act
        filter_obj = make_allpass(frequency, samplerate)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        assert filter_obj.order == 2, "All-pass filter should have order 2"
        assert len(filter_obj.a_coeffs) == 3, "Should have 3 a coefficients"
        assert len(filter_obj.b_coeffs) == 3, "Should have 3 b coefficients"
        
        # Verify mathematical calculations
        w0 = tau * frequency / samplerate
        _sin = sin(w0)
        _cos = cos(w0)
        alpha = _sin / (2 * expected_q_factor)
        
        expected_b0 = 1 - alpha
        expected_b1 = -2 * _cos
        expected_b2 = 1 + alpha
        
        # Check coefficient values with tolerance for floating point precision
        tolerance = 1e-10
        assert abs(filter_obj.b_coeffs[0] - expected_b0) < tolerance
        assert abs(filter_obj.b_coeffs[1] - expected_b1) < tolerance
        assert abs(filter_obj.b_coeffs[2] - expected_b2) < tolerance
        
        print(f"Default Q factor test passed with coefficients: {filter_obj.a_coeffs + filter_obj.b_coeffs}")

    def test_make_allpass_with_custom_q_factor(self):
        """Test all-pass filter creation with custom Q factor"""
        # Arrange
        frequency = 2000
        samplerate = 44100
        custom_q_factor = 0.5
        
        # Act
        filter_obj = make_allpass(frequency, samplerate, custom_q_factor)
        
        # Create another filter with default Q factor for comparison
        default_filter = make_allpass(frequency, samplerate)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        assert filter_obj.order == 2, "All-pass filter should have order 2"
        
        # Verify that custom Q factor produces different coefficients
        assert filter_obj.a_coeffs != default_filter.a_coeffs, "Custom Q factor should produce different coefficients"
        assert filter_obj.b_coeffs != default_filter.b_coeffs, "Custom Q factor should produce different coefficients"
        
        # Verify mathematical relationships are maintained
        w0 = tau * frequency / samplerate
        _sin = sin(w0)
        _cos = cos(w0)
        alpha = _sin / (2 * custom_q_factor)
        
        expected_b0 = 1 - alpha
        expected_b1 = -2 * _cos
        expected_b2 = 1 + alpha
        
        tolerance = 1e-10
        assert abs(filter_obj.b_coeffs[0] - expected_b0) < tolerance
        assert abs(filter_obj.b_coeffs[1] - expected_b1) < tolerance
        assert abs(filter_obj.b_coeffs[2] - expected_b2) < tolerance
        
        print(f"Custom Q factor test passed with Q={custom_q_factor}")

    def test_make_allpass_low_frequency(self):
        """Test all-pass filter with very low frequency"""
        # Arrange
        frequency = 50  # Very low frequency
        samplerate = 48000
        
        # Act
        filter_obj = make_allpass(frequency, samplerate)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        assert filter_obj.order == 2, "All-pass filter should have order 2"
        
        # Verify coefficients are valid (not NaN or infinite)
        for coeff in filter_obj.a_coeffs + filter_obj.b_coeffs:
            assert not (coeff != coeff), "Coefficients should not be NaN"  # NaN check
            assert abs(coeff) < float('inf'), "Coefficients should not be infinite"
        
        # For low frequencies, w0 should be small, affecting the calculations
        w0 = tau * frequency / samplerate
        assert w0 < 0.1, "w0 should be small for low frequencies"
        
        print(f"Low frequency test passed with frequency={frequency}Hz, w0={w0}")

    def test_make_allpass_high_frequency_near_nyquist(self):
        """Test all-pass filter with high frequency near Nyquist limit"""
        # Arrange
        frequency = 20000  # High frequency
        samplerate = 44100  # Nyquist frequency is 22050 Hz
        
        # Act
        filter_obj = make_allpass(frequency, samplerate)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        assert filter_obj.order == 2, "All-pass filter should have order 2"
        
        # Verify coefficients are valid and stable
        for coeff in filter_obj.a_coeffs + filter_obj.b_coeffs:
            assert not (coeff != coeff), "Coefficients should not be NaN"  # NaN check
            assert abs(coeff) < float('inf'), "Coefficients should not be infinite"
        
        # Verify frequency is below Nyquist
        nyquist_freq = samplerate / 2
        assert frequency < nyquist_freq, f"Frequency {frequency} should be below Nyquist frequency {nyquist_freq}"
        
        print(f"High frequency test passed with frequency={frequency}Hz, Nyquist={nyquist_freq}Hz")

    def test_make_allpass_very_high_q_factor(self):
        """Test all-pass filter with very high Q factor"""
        # Arrange
        frequency = 1000
        samplerate = 48000
        high_q_factor = 10.0  # Very high Q factor
        
        # Act
        filter_obj = make_allpass(frequency, samplerate, high_q_factor)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        assert filter_obj.order == 2, "All-pass filter should have order 2"
        
        # Verify coefficients are valid
        for coeff in filter_obj.a_coeffs + filter_obj.b_coeffs:
            assert not (coeff != coeff), "Coefficients should not be NaN"  # NaN check
            assert abs(coeff) < float('inf'), "Coefficients should not be infinite"
        
        # High Q factor should result in smaller alpha value
        w0 = tau * frequency / samplerate
        _sin = sin(w0)
        alpha = _sin / (2 * high_q_factor)
        
        # Alpha should be smaller with high Q factor
        default_alpha = _sin / (2 * (1 / sqrt(2)))
        assert alpha < default_alpha, "High Q factor should produce smaller alpha value"
        
        print(f"High Q factor test passed with Q={high_q_factor}, alpha={alpha}")

    def test_make_allpass_very_low_q_factor(self):
        """Test all-pass filter with very low Q factor"""
        # Arrange
        frequency = 1500
        samplerate = 48000
        low_q_factor = 0.1  # Very low Q factor
        
        # Act
        filter_obj = make_allpass(frequency, samplerate, low_q_factor)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        assert filter_obj.order == 2, "All-pass filter should have order 2"
        
        # Verify coefficients are valid
        for coeff in filter_obj.a_coeffs + filter_obj.b_coeffs:
            assert not (coeff != coeff), "Coefficients should not be NaN"  # NaN check
            assert abs(coeff) < float('inf'), "Coefficients should not be infinite"
        
        # Low Q factor should result in larger alpha value
        w0 = tau * frequency / samplerate
        _sin = sin(w0)
        alpha = _sin / (2 * low_q_factor)
        
        # Alpha should be larger with low Q factor
        default_alpha = _sin / (2 * (1 / sqrt(2)))
        assert alpha > default_alpha, "Low Q factor should produce larger alpha value"
        
        print(f"Low Q factor test passed with Q={low_q_factor}, alpha={alpha}")

    def test_make_allpass_coefficient_symmetry(self):
        """Test that all-pass filter maintains coefficient symmetry"""
        # Arrange
        frequency = 800
        samplerate = 48000
        
        # Act
        filter_obj = make_allpass(frequency, samplerate)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        
        # Extract coefficients
        a_coeffs = filter_obj.a_coeffs
        b_coeffs = filter_obj.b_coeffs
        
        # Verify all-pass filter symmetry property: b_coeffs should be reverse of a_coeffs
        tolerance = 1e-10
        assert abs(b_coeffs[0] - a_coeffs[2]) < tolerance, "b0 should equal a2"
        assert abs(b_coeffs[1] - a_coeffs[1]) < tolerance, "b1 should equal a1"
        assert abs(b_coeffs[2] - a_coeffs[0]) < tolerance, "b2 should equal a0"
        
        print(f"Coefficient symmetry test passed: a_coeffs={a_coeffs}, b_coeffs={b_coeffs}")

    def test_make_allpass_different_sample_rates(self):
        """Test all-pass filter with different sample rates"""
        # Arrange
        frequency = 1000
        samplerate1 = 44100
        samplerate2 = 96000
        
        # Act
        filter1 = make_allpass(frequency, samplerate1)
        filter2 = make_allpass(frequency, samplerate2)
        
        # Assert
        assert isinstance(filter1, IIRFilter), "Should return an IIRFilter instance"
        assert isinstance(filter2, IIRFilter), "Should return an IIRFilter instance"
        
        # Different sample rates should produce different coefficients
        assert filter1.a_coeffs != filter2.a_coeffs, "Different sample rates should produce different a coefficients"
        assert filter1.b_coeffs != filter2.b_coeffs, "Different sample rates should produce different b coefficients"
        
        # Both should have valid coefficients
        for coeff in filter1.a_coeffs + filter1.b_coeffs + filter2.a_coeffs + filter2.b_coeffs:
            assert not (coeff != coeff), "Coefficients should not be NaN"  # NaN check
            assert abs(coeff) < float('inf'), "Coefficients should not be infinite"
        
        print(f"Different sample rates test passed: {samplerate1}Hz vs {samplerate2}Hz")

    def test_make_allpass_mathematical_consistency(self):
        """Test mathematical consistency of calculated coefficients"""
        # Arrange
        frequency = 1200
        samplerate = 48000
        q_factor = 0.8
        
        # Act
        filter_obj = make_allpass(frequency, samplerate, q_factor)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        
        # Manually calculate expected coefficients
        w0 = tau * frequency / samplerate
        _sin = sin(w0)
        _cos = cos(w0)
        alpha = _sin / (2 * q_factor)
        
        expected_b0 = 1 - alpha
        expected_b1 = -2 * _cos
        expected_b2 = 1 + alpha
        
        # Verify mathematical relationships
        tolerance = 1e-10
        assert abs(filter_obj.b_coeffs[0] - expected_b0) < tolerance, f"b0 calculation mismatch"
        assert abs(filter_obj.b_coeffs[1] - expected_b1) < tolerance, f"b1 calculation mismatch"
        assert abs(filter_obj.b_coeffs[2] - expected_b2) < tolerance, f"b2 calculation mismatch"
        
        # Verify denominator coefficients match expected pattern
        assert abs(filter_obj.a_coeffs[0] - expected_b2) < tolerance, f"a0 should equal b2"
        assert abs(filter_obj.a_coeffs[1] - expected_b1) < tolerance, f"a1 should equal b1"
        assert abs(filter_obj.a_coeffs[2] - expected_b0) < tolerance, f"a2 should equal b0"
        
        print(f"Mathematical consistency test passed with calculated coefficients")

    def test_make_allpass_return_type_and_structure(self):
        """Test return type and structure validation"""
        # Arrange
        frequency = 1000
        samplerate = 48000
        
        # Act
        filter_obj = make_allpass(frequency, samplerate)
        
        # Assert
        assert isinstance(filter_obj, IIRFilter), "Should return an IIRFilter instance"
        assert filter_obj.order == 2, "All-pass filter should have order 2"
        
        # Verify coefficient structure
        assert len(filter_obj.a_coeffs) == 3, "Should have exactly 3 a coefficients"
        assert len(filter_obj.b_coeffs) == 3, "Should have exactly 3 b coefficients"
        
        # Verify all coefficients are numbers
        for coeff in filter_obj.a_coeffs + filter_obj.b_coeffs:
            assert isinstance(coeff, (int, float)), "All coefficients should be numeric"
            assert not (coeff != coeff), "Coefficients should not be NaN"  # NaN check
        
        # Verify filter has proper initialization
        assert hasattr(filter_obj, 'input_history'), "Filter should have input_history attribute"
        assert hasattr(filter_obj, 'output_history'), "Filter should have output_history attribute"
        
        print(f"Return type and structure test passed")
